export {anatomy as scrollAreaAnatomy} from '@zag-js/scroll-area';
export * from './createScrollArea.svelte.js';
export * as ScrollArea from './ScrollArea.js';
export type {ScrollAreaContentProps} from './ScrollAreaContent.svelte';
export * from './ScrollAreaContext.svelte.js';
export type {ScrollAreaCornerProps} from './ScrollAreaCorner.svelte';
export type {ScrollAreaRootProps} from './ScrollAreaRoot.svelte';
export type {ScrollAreaScrollbarProps} from './ScrollAreaScrollbar.svelte';
export type {ScrollAreaThumbProps} from './ScrollAreaThumb.svelte';
export type {ScrollAreaViewportProps} from './ScrollAreaViewport.svelte';
